/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as React from 'react';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import model from "./wagon.glb";
import { GroupProps, useLoader } from '@react-three/fiber';
import * as THREE from 'three';
import { useGLTF } from "@react-three/drei";

export const Train = React.forwardRef(function Train(props: GroupProps, ref: React.Ref<THREE.Group>): React.JSX.Element {
  const loaded = useLoader(GLTFLoader, model);
  const res = loaded instanceof Array ? loaded[0] : loaded;
  const materials = res.materials;
  const nodes = res.nodes as any;
  return (
  <group {...props} dispose={null} ref={ref}>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-AC_unit'].geometry}
      material={materials['[Color_F21]']}
      position={[0.596, 3.658, -9.127]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={1.027}
    />
    <group position={[-1.123, 3.147, -6.89]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Air_intake_1'].geometry}
        material={materials['Air intake']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Air_intake_2'].geometry}
        material={materials['[Color_F21]']}
      />
    </group>
    <group position={[-1.123, 3.147, -0.582]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Air_intake_1'].geometry}
        material={materials['Air intake']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Air_intake_2'].geometry}
        material={materials['[Color_F21]']}
      />
    </group>
    <group position={[-1.123, 3.147, 5.726]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Air_intake_1'].geometry}
        material={materials['Air intake']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Air_intake_2'].geometry}
        material={materials['[Color_F21]']}
      />
    </group>
    <group position={[1.082, 3.147, -0.582]} rotation={[0, 0, Math.PI]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Air_intake_1'].geometry}
        material={materials['Air intake']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Air_intake_2'].geometry}
        material={materials['[Color_F21]']}
      />
    </group>
    <group position={[1.082, 3.147, 5.726]} rotation={[0, 0, Math.PI]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Air_intake_1'].geometry}
        material={materials['Air intake']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Air_intake_2'].geometry}
        material={materials['[Color_F21]']}
      />
    </group>
    <group position={[1.082, 3.147, -6.89]} rotation={[0, 0, Math.PI]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Air_intake_1'].geometry}
        material={materials['Air intake']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Air_intake_2'].geometry}
        material={materials['[Color_F21]']}
      />
    </group>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Box#A'].geometry}
      material={materials['[Color_006]']}
      position={[1.161, 0.219, -2.538]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={[0.822, 1.382, 0.342]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Box#A#1'].geometry}
      material={materials['[Color_006]']}
      position={[1.264, 0.321, 3.03]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={[1.027, 0.85, 0.56]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Box#A001'].geometry}
      material={materials['[Color_006]']}
      position={[1.161, 0.219, -1.305]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={[0.822, 1.382, 0.529]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Box#A002'].geometry}
      material={materials['[Color_006]']}
      position={[1.161, 0.321, 1.53]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={[0.822, 1.204, 0.423]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Box#A003'].geometry}
      material={materials['[Color_006]']}
      position={[1.161, 0.321, 0.493]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={[0.514, 1.204, 0.156]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Box#A004'].geometry}
      material={materials['[Color_006]']}
      position={[1.11, 0.373, 1.006]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={[0.462, 1.116, 0.156]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Box#A005'].geometry}
      material={materials['[Color_006]']}
      position={[1.161, 0.219, -3.668]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={[0.822, 1.382, 0.342]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Box#A006'].geometry}
      material={materials['[Color_006]']}
      position={[1.161, 0.219, -4.798]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={[0.822, 1.382, 0.342]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Box#A007'].geometry}
      material={materials['[Color_006]']}
      position={[-0.38, 0.219, 1.315]}
      rotation={[Math.PI, 0, 0]}
      scale={[-0.822, -1.382, -0.342]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Box#A008'].geometry}
      material={materials['[Color_006]']}
      position={[-0.38, 0.219, -3.925]}
      rotation={[Math.PI, 0, 0]}
      scale={[-0.822, -1.382, -0.265]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Box#A009'].geometry}
      material={materials['[Color_006]']}
      position={[-0.38, 0.219, -0.945]}
      rotation={[Math.PI, 0, 0]}
      scale={[-0.822, -1.382, -0.342]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Box#A010'].geometry}
      material={materials['[Color_006]']}
      position={[-0.38, 0.219, 0.185]}
      rotation={[Math.PI, 0, 0]}
      scale={[-0.822, -1.382, -0.342]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Box#A011'].geometry}
      material={materials['[Color_006]']}
      position={[-0.38, 0.219, -2.178]}
      rotation={[Math.PI, 0, 0]}
      scale={[-0.822, -1.382, -0.529]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Box#A012'].geometry}
      material={materials['[Color_006]']}
      position={[-0.38, 0.398, 3.678]}
      rotation={[Math.PI, 0, 0]}
      scale={[-0.822, -1.073, -0.342]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Box#A013'].geometry}
      material={materials['[Color_006]']}
      position={[-0.38, 0.278, 2.445]}
      rotation={[Math.PI, 0, 0]}
      scale={[-0.822, -1.279, -0.171]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Box#A014'].geometry}
      material={materials['[Color_006]']}
      position={[0.997, 0.579, 9.47]}
      rotation={[0, 0, Math.PI]}
      scale={[-0.164, -0.76, -0.053]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Box#A015'].geometry}
      material={materials['[Color_006]']}
      position={[0.997, 0.579, -9.349]}
      scale={[0.164, 0.76, 0.053]}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Box#C'].geometry}
      material={materials['[Color_F21]']}
      position={[0.36, 3.658, 3.094]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Bracket#B'].geometry}
      material={materials['[Color_F13]']}
      position={[-0.416, 1.945, 9.789]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={1.027}
    />
    <group
      position={[0.596, 3.64, -4.88]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={[1.027, 1.027, 1.233]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Brake_resistance_1'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Brake_resistance_2'].geometry}
        material={materials['[Color_F21]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Brake_resistance_3'].geometry}
        material={materials['[Fencing_Mesh_Blue]']}
      />
    </group>
    <group
      position={[0.596, 3.64, -4.382]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={[1.027, 1.027, 1.233]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Brake_resistance_1'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Brake_resistance_2'].geometry}
        material={materials['[Color_F21]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Brake_resistance_3'].geometry}
        material={materials['[Fencing_Mesh_Blue]']}
      />
    </group>
    <group
      position={[0.596, 3.64, -3.884]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={[1.027, 1.027, 1.233]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Brake_resistance_1'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Brake_resistance_2'].geometry}
        material={materials['[Color_F21]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Brake_resistance_3'].geometry}
        material={materials['[Fencing_Mesh_Blue]']}
      />
    </group>
    <group
      position={[0.596, 3.64, -3.386]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={[1.027, 1.027, 1.233]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Brake_resistance_1'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Brake_resistance_2'].geometry}
        material={materials['[Color_F21]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Brake_resistance_3'].geometry}
        material={materials['[Fencing_Mesh_Blue]']}
      />
    </group>
    <group
      position={[0.596, 3.64, -2.888]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={[1.027, 1.027, 1.233]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Brake_resistance_1'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Brake_resistance_2'].geometry}
        material={materials['[Color_F21]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Brake_resistance_3'].geometry}
        material={materials['[Fencing_Mesh_Blue]']}
      />
    </group>
    <group position={[1.264, 1.071, 8.163]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Cab_interior_1'].geometry}
        material={materials['[Color_000]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Cab_interior_2'].geometry}
        material={materials['[Color_003]']}
      />
    </group>
    <group position={[-1.305, 1.071, -8.042]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Cab_interior_1'].geometry}
        material={materials['[Color_000]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Cab_interior_2'].geometry}
        material={materials['[Color_003]']}
      />
    </group>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Cable'].geometry}
      material={materials['[Color_007]']}
      position={[0.328, 3.658, 2.897]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={1.027}
    />
    <group position={[1.103, 2.808, -9.608]} rotation={[-Math.PI, 0.055, -Math.PI]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Display_1'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Display_2'].geometry}
        material={materials['[Color_009]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Display_3'].geometry}
        material={materials['[Color_000]']}
      />
    </group>
    <group position={[-1.259, 0.887, -7.554]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_1'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_2'].geometry}
        material={materials['[Color_000]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_3'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_4'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
    </group>
    <group position={[-1.259, 0.887, -7.554]} rotation={[Math.PI, 0, 0]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_1'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_2'].geometry}
        material={materials['[Color_000]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_3'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_4'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
    </group>
    <group position={[-1.259, 0.887, 7.675]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_1'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_2'].geometry}
        material={materials['[Color_000]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_3'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_4'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
    </group>
    <group position={[-1.259, 0.887, 7.675]} rotation={[Math.PI, 0, 0]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_1'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_2'].geometry}
        material={materials['[Color_000]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_3'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_4'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
    </group>
    <group position={[1.218, 0.887, 7.675]} rotation={[0, 0, Math.PI]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_1'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_2'].geometry}
        material={materials['[Color_000]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_3'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_4'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
    </group>
    <group position={[1.218, 0.887, 7.675]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_1'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_2'].geometry}
        material={materials['[Color_000]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_3'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_4'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
    </group>
    <group position={[1.218, 0.887, -7.554]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_1'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_2'].geometry}
        material={materials['[Color_000]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_3'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_4'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
    </group>
    <group position={[1.218, 0.887, -7.554]} rotation={[0, 0, Math.PI]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_1'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_2'].geometry}
        material={materials['[Color_000]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_3'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Door#A_4'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
    </group>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Footstep#B'].geometry}
      material={materials['[Color_006]']}
      position={[-1.253, 0.558, 7.267]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Footstep#B001'].geometry}
      material={materials['[Color_006]']}
      position={[1.212, 0.558, -7.146]}
      scale={1.027}
    />
    <group position={[1.315, 0.815, -9.669]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Frame_X10p'].geometry}
        material={materials['[Color_000]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Frame_X10p_1'].geometry}
        material={materials['[Color_F21]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Frame_X10p_2'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Frame_X10p_3'].geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Frame_X10p_4'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Frame_X10p_5'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Frame_X10p_6'].geometry}
        material={materials['[Color_007]']}
      />
    </group>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Footstep#A'].geometry}
      material={materials['[Color_006]']}
      position={[-1.274, 0.589, -9.121]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Footstep#A001'].geometry}
      material={materials['[Color_006]']}
      position={[-1.274, 0.589, 8.78]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Footstep#A002'].geometry}
      material={materials['[Color_006]']}
      position={[1.315, 0.589, -9.121]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Footstep#A003'].geometry}
      material={materials['[Color_006]']}
      position={[1.315, 0.589, 8.78]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={1.027}
    />
    <group position={[0.365, 1.071, 9.79]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Gable_door_1'].geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Gable_door_2'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Gable_door_3'].geometry}
        material={materials['[Color_000]']}
      />
    </group>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Handrail#B'].geometry}
      material={materials['[Color_F21]']}
      position={[-1.356, 1.128, -9.291]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Handrail#B001'].geometry}
      material={materials['[Color_F21]']}
      position={[-1.356, 1.128, -8.489]}
      rotation={[Math.PI, 0, 0]}
      scale={-1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Handrail#B002'].geometry}
      material={materials['[Color_F21]']}
      position={[-1.356, 1.128, 8.61]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Handrail#B003'].geometry}
      material={materials['[Color_F21]']}
      position={[-1.356, 1.128, 9.411]}
      rotation={[Math.PI, 0, 0]}
      scale={-1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Handrail#B004'].geometry}
      material={materials['[Color_F21]']}
      position={[1.315, 1.128, 9.411]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Handrail#B005'].geometry}
      material={materials['[Color_F21]']}
      position={[1.315, 1.128, 8.61]}
      rotation={[0, 0, Math.PI]}
      scale={-1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Handrail#B006'].geometry}
      material={materials['[Color_F21]']}
      position={[1.315, 1.128, -8.489]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Handrail#B007'].geometry}
      material={materials['[Color_F21]']}
      position={[1.315, 1.128, -9.291]}
      rotation={[0, 0, Math.PI]}
      scale={-1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Handrail#C'].geometry}
      material={materials['[Color_F21]']}
      position={[-1.356, 1.878, -9.26]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Handrail#C001'].geometry}
      material={materials['[Color_F21]']}
      position={[-1.356, 1.878, 8.641]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Handrail#C002'].geometry}
      material={materials['[Color_F21]']}
      position={[1.315, 1.878, 8.641]}
      rotation={[0, 0, Math.PI]}
      scale={-1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Handrail#C003'].geometry}
      material={materials['[Color_F21]']}
      position={[1.315, 1.878, -9.26]}
      rotation={[0, 0, Math.PI]}
      scale={-1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Handrail#E'].geometry}
      material={materials['[Color_F21]']}
      position={[-0.411, 2.13, 9.79]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Handrail#E001'].geometry}
      material={materials['[Color_F21]']}
      position={[0.37, 2.13, 9.79]}
      rotation={[0, 0, Math.PI]}
      scale={-1.027}
    />
    <group position={[1.182, 1.166, -9.667]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Headlamp_1'].geometry}
        material={materials['[Color_003]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Headlamp_2'].geometry}
        material={materials.Material}
      />
    </group>
    <group position={[0.982, 1.166, -9.667]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Headlamp_1'].geometry}
        material={materials['[Color_003]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Headlamp_2'].geometry}
        material={materials.Material}
      />
    </group>
    <group position={[-1.023, 1.166, -9.667]} rotation={[0, 0, Math.PI]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Headlamp001_1'].geometry}
        material={materials['[Color_003]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Headlamp001_2'].geometry}
        material={materials['[Color_001]']}
      />
    </group>
    <group position={[-1.222, 1.166, -9.667]} rotation={[0, 0, Math.PI]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Headlamp001_1'].geometry}
        material={materials['[Color_003]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Headlamp001_2'].geometry}
        material={materials['[Color_001]']}
      />
    </group>
    <group position={[0.07, 3.187, -9.658]} rotation={[0, 0, Math.PI]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Headlamp002_1'].geometry}
        material={materials['[Color_003]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Headlamp002_2'].geometry}
        material={materials['[Color_A11]']}
      />
    </group>
    <group position={[-0.292, 3.187, -9.658]} rotation={[0, 0, Math.PI]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Headlamp002_1'].geometry}
        material={materials['[Color_003]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Headlamp002_2'].geometry}
        material={materials['[Color_A11]']}
      />
    </group>
    <group position={[-0.111, 3.187, -9.658]} rotation={[0, 0, Math.PI]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Headlamp001_1'].geometry}
        material={materials['[Color_003]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Headlamp001_2'].geometry}
        material={materials['[Color_001]']}
      />
    </group>
    <group position={[-0.111, 3.187, 9.779]} rotation={[-Math.PI, 0, 0]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Headlamp002_1'].geometry}
        material={materials['[Color_003]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Headlamp002_2'].geometry}
        material={materials['[Color_A11]']}
      />
    </group>
    <group position={[0.07, 3.187, 9.779]} rotation={[-Math.PI, 0, 0]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Headlamp001_1'].geometry}
        material={materials['[Color_003]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Headlamp001_2'].geometry}
        material={materials['[Color_001]']}
      />
    </group>
    <group position={[0.251, 3.187, 9.779]} rotation={[-Math.PI, 0, 0]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Headlamp002_1'].geometry}
        material={materials['[Color_003]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Headlamp002_2'].geometry}
        material={materials['[Color_A11]']}
      />
    </group>
    <group position={[0.281, 3.648, 5.422]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Insulator'].geometry}
        material={materials['[Color_007]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Insulator_1'].geometry}
        material={materials['[Color_006]']}
      />
    </group>
    <group position={[1.295, 0.887, -9.648]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Interiour#A_1'].geometry}
        material={materials['[Color_E04]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Interiour#A_2'].geometry}
        material={materials['[Color_003]']}
      />
    </group>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Lamp_box'].geometry}
      material={materials['[Color_F13]']}
      position={[0.791, 1.154, -9.657]}
      rotation={[0, 0, Math.PI]}
      scale={-1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Lamp_box001'].geometry}
      material={materials['[Color_F13]']}
      position={[-0.832, 1.154, -9.657]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Metal_plate'].geometry}
      material={materials['[Color_F21]']}
      position={[-0.431, 0.917, -9.699]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Metal_plate001'].geometry}
      material={materials['[Color_F21]']}
      position={[0.391, 0.917, -9.699]}
      rotation={[0, 0, Math.PI]}
      scale={-1.027}
    />
    <group position={[-1.38, 2.355, -9.328]} rotation={[Math.PI, -0.262, Math.PI]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object014_1'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object014_2'].geometry}
        material={materials['[Color_003]']}
      />
    </group>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['G-Object015'].geometry}
      material={materials['[Color_008]']}
      position={[-1.331, 2.55, -9.372]}
      rotation={[Math.PI, -Math.PI / 6, Math.PI]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['G-Object016'].geometry}
      material={materials['[Color_008]']}
      position={[-1.283, 2.666, -9.382]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={1.027}
    />
    <group position={[1.339, 2.355, -9.328]} rotation={[0, -0.262, Math.PI]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object017_1'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object017_2'].geometry}
        material={materials['[Color_003]']}
      />
    </group>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['G-Object018'].geometry}
      material={materials['[Color_008]']}
      position={[1.29, 2.55, -9.372]}
      rotation={[0, -Math.PI / 6, -Math.PI]}
      scale={-1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['G-Object019'].geometry}
      material={materials['[Color_008]']}
      position={[1.242, 2.666, -9.382]}
      rotation={[0, 0, Math.PI]}
      scale={-1.027}
    />
    <group position={[1.314, 2.355, 9.42]} rotation={[0, 1.501, 0]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object020_1'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object020_2'].geometry}
        material={materials['[Color_003]']}
      />
    </group>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['G-Object021'].geometry}
      material={materials['[Color_008]']}
      position={[1.308, 2.55, 9.487]}
      rotation={[0, 1.501, 0]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['G-Object022'].geometry}
      material={materials['[Color_008]']}
      position={[1.242, 2.666, 9.503]}
      scale={1.027}
    />
    <group position={[1.185, 2.638, 7.913]} rotation={[Math.PI, -1.501, Math.PI]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object023_1'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object023_2'].geometry}
        material={materials['[Color_003]']}
      />
    </group>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['G-Object024'].geometry}
      material={materials['[Color_008]']}
      position={[1.19, 2.833, 7.846]}
      rotation={[Math.PI, -1.501, Math.PI]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['G-Object025'].geometry}
      material={materials['[Color_008]']}
      position={[1.257, 2.949, 7.83]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={1.027}
    />
    <group position={[-1.355, 2.355, 9.42]} rotation={[Math.PI, 1.501, 0]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object026_1'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object026_2'].geometry}
        material={materials['[Color_003]']}
      />
    </group>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['G-Object027'].geometry}
      material={materials['[Color_008]']}
      position={[-1.349, 2.55, 9.487]}
      rotation={[Math.PI, 1.501, 0]}
      scale={-1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['G-Object028'].geometry}
      material={materials['[Color_008]']}
      position={[-1.283, 2.666, 9.503]}
      rotation={[-Math.PI, 0, 0]}
      scale={-1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Vent'].geometry}
      material={materials['[Color_F21]']}
      position={[0.908, 3.621, 8.694]}
      rotation={[Math.PI, 0, -3.078]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Vent001'].geometry}
      material={materials['[Color_F21]']}
      position={[-0.948, 3.621, 8.694]}
      rotation={[0, 0, -3.078]}
      scale={-1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Vent002'].geometry}
      material={materials['[Color_F21]']}
      position={[-0.948, 3.621, 4.585]}
      rotation={[0, 0, -3.078]}
      scale={-1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Vent003'].geometry}
      material={materials['[Color_F21]']}
      position={[-0.948, 3.621, 1.503]}
      rotation={[0, 0, -3.078]}
      scale={-1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Vent004'].geometry}
      material={materials['[Color_F21]']}
      position={[0.908, 3.621, -8.573]}
      rotation={[-Math.PI, 0, 0.063]}
      scale={-1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Vent005'].geometry}
      material={materials['[Color_F21]']}
      position={[0.908, 3.621, -1.382]}
      rotation={[-Math.PI, 0, 0.063]}
      scale={-1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Vent006'].geometry}
      material={materials['[Color_F21]']}
      position={[0.908, 3.621, -4.464]}
      rotation={[-Math.PI, 0, 0.063]}
      scale={-1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Vent007'].geometry}
      material={materials['[Color_F21]']}
      position={[-0.948, 3.621, -8.573]}
      rotation={[0, 0, 0.063]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Vent008'].geometry}
      material={materials['[Color_F21]']}
      position={[-0.948, 3.621, 7.502]}
      rotation={[0, 0, -3.078]}
      scale={-1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['C-Vent009'].geometry}
      material={materials['[Color_F21]']}
      position={[0.908, 3.621, -7.381]}
      rotation={[-Math.PI, 0, 0.063]}
      scale={-1.027}
    />
    <group position={[-1.352, 1.996, -6.807]} rotation={[Math.PI, 0, -3.055]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_1'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_2'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_3'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
    </group>
    <group position={[-1.352, 1.996, -3.653]} rotation={[Math.PI, 0, -3.055]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_1'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_2'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_3'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
    </group>
    <group position={[-1.352, 1.996, -2.076]} rotation={[Math.PI, 0, -3.055]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_1'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_2'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_3'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
    </group>
    <group position={[-1.352, 1.996, 1.078]} rotation={[Math.PI, 0, -3.055]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_1'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_2'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_3'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
    </group>
    <group position={[-1.352, 1.996, 2.655]} rotation={[Math.PI, 0, -3.055]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_1'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_2'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_3'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
    </group>
    <group position={[-1.352, 1.996, 5.809]} rotation={[Math.PI, 0, -3.055]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_1'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_2'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_3'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
    </group>
    <group position={[1.311, 1.996, -6.807]} rotation={[0, 0, -3.055]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_1'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_2'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_3'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
    </group>
    <group position={[1.311, 1.996, 5.809]} rotation={[0, 0, -3.055]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_1'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_2'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_3'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
    </group>
    <group position={[1.311, 1.996, 1.078]} rotation={[0, 0, -3.055]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_1'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_2'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_3'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
    </group>
    <group position={[1.311, 1.996, -2.076]} rotation={[0, 0, -3.055]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_1'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_2'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_3'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
    </group>
    <group position={[1.311, 1.996, -3.653]} rotation={[0, 0, -3.055]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_1'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_2'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_3'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
    </group>
    <group position={[1.311, 1.996, 2.655]} rotation={[0, 0, -3.055]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_1'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_2'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#A_3'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
    </group>
    <group position={[-1.352, 1.996, -5.23]} rotation={[Math.PI, 0, -3.055]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_1'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_2'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_3'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_4'].geometry}
        material={materials['[Color_003]']}
      />
    </group>
    <group position={[-1.352, 1.996, -0.499]} rotation={[Math.PI, 0, -3.055]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_1'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_2'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_3'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_4'].geometry}
        material={materials['[Color_003]']}
      />
    </group>
    <group position={[-1.352, 1.996, 4.232]} rotation={[Math.PI, 0, -3.055]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_1'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_2'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_3'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_4'].geometry}
        material={materials['[Color_003]']}
      />
    </group>
    <group position={[1.311, 1.996, 4.232]} rotation={[0, 0, -3.055]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_1'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_2'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_3'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_4'].geometry}
        material={materials['[Color_003]']}
      />
    </group>
    <group position={[1.311, 1.996, -5.23]} rotation={[0, 0, -3.055]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_1'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_2'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_3'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_4'].geometry}
        material={materials['[Color_003]']}
      />
    </group>
    <group position={[1.311, 1.996, -0.499]} rotation={[0, 0, -3.055]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_1'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_2'].geometry}
        material={materials['[Color_008]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_3'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#B_4'].geometry}
        material={materials['[Color_003]']}
      />
    </group>
    <group position={[-1.352, 1.996, -9.296]} rotation={[Math.PI, 0, -3.055]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#C_1'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#C_2'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#C_3'].geometry}
        material={materials['[Color_003]']}
      />
    </group>
    <group position={[1.311, 1.996, -9.296]} rotation={[0, 0, -3.055]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#C_1'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#C_2'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#C_3'].geometry}
        material={materials['[Color_003]']}
      />
    </group>
    <group position={[-1.352, 1.996, 8.338]} rotation={[Math.PI, 0, -3.055]} scale={1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#C_1'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#C_2'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#C_3'].geometry}
        material={materials['[Color_003]']}
      />
    </group>
    <group position={[1.311, 1.996, 8.338]} rotation={[0, 0, -3.055]} scale={-1.027}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#C_1'].geometry}
        material={materials['[Color_F13]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#C_2'].geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Window#C_3'].geometry}
        material={materials['[Color_003]']}
      />
    </group>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['_C-Wiper_(Loose_Mesh)'].geometry}
      material={materials['[Color_009]']}
      position={[0.35, 1.912, -9.64]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['G-Object004'].geometry}
      material={materials['[Color_009]']}
      position={[0.006, 1.905, -9.703]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['G-Object005'].geometry}
      material={materials['[Color_009]']}
      position={[0.259, 2.16, -9.684]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['_C-Wiper_(Loose_Mesh)001'].geometry}
      material={materials['[Color_009]']}
      position={[-0.479, 1.912, -9.638]}
      rotation={[Math.PI, -0.055, Math.PI]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['G-Object006'].geometry}
      material={materials['[Color_009]']}
      position={[-0.826, 1.905, -9.681]}
      rotation={[Math.PI, -0.055, Math.PI]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['G-Object007'].geometry}
      material={materials['[Color_009]']}
      position={[-0.573, 2.16, -9.676]}
      rotation={[Math.PI, -0.055, Math.PI]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['_C-Wiper_(Loose_Mesh)002'].geometry}
      material={materials['[Color_009]']}
      position={[1.179, 1.912, -9.596]}
      rotation={[-Math.PI, 0.055, -Math.PI]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['G-Object008'].geometry}
      material={materials['[Color_009]']}
      position={[0.838, 1.905, -9.678]}
      rotation={[-Math.PI, 0.055, -Math.PI]}
      scale={1.027}
    />
    <mesh
      castShadow
      receiveShadow
      geometry={nodes['G-Object009'].geometry}
      material={materials['[Color_009]']}
      position={[1.089, 2.16, -9.645]}
      rotation={[-Math.PI, 0.055, -Math.PI]}
      scale={1.027}
    />
  </group>
  )
});

useGLTF.preload(model);
