/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react';
import * as React from 'react';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import model from "../../assets/wagon.glb";
import { GroupProps, useLoader } from '@react-three/fiber';
import * as THREE from 'three';

export const Train = React.forwardRef(function Train(props: GroupProps, ref: React.Ref<THREE.Group>): React.JSX.Element {
  const loaded = useLoader(GLTFLoader, model);
  const res = loaded instanceof Array ? loaded[0] : loaded;
  const materials = res.materials;
  const nodes = res.nodes as any;
  return (
    <group {...props} dispose={null} ref={ref}>
      <group position={[0.493, 0.706, 9.488]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Cap_1'].geometry}
          material={materials['[Color_D01]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Cap_2'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Cap_3'].geometry}
          material={materials['[Color_F21]']}
        />
      </group>
      <group position={[-0.007, 0.706, 9.488]} rotation={[-Math.PI, 0, 0]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Cap_1'].geometry}
          material={materials['[Color_D01]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Cap_2'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Cap_3'].geometry}
          material={materials['[Color_F21]']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-AC_unit'].geometry}
        material={materials['[Color_F21]']}
        position={[-0.357, 3.575, 8.456]}
      />
      <group position={[1.316, 3.077, 6.278]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Air_intake_1'].geometry}
          material={materials['Air intake']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Air_intake_2'].geometry}
          material={materials['[Color_F21]']}
        />
      </group>
      <group position={[1.316, 3.077, 0.138]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Air_intake_1'].geometry}
          material={materials['Air intake']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Air_intake_2'].geometry}
          material={materials['[Color_F21]']}
        />
      </group>
      <group position={[1.316, 3.077, -6.002]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Air_intake_1'].geometry}
          material={materials['Air intake']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Air_intake_2'].geometry}
          material={materials['[Color_F21]']}
        />
      </group>
      <group position={[-0.831, 3.077, 0.138]} rotation={[-Math.PI, 0, 0]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Air_intake_1'].geometry}
          material={materials['Air intake']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Air_intake_2'].geometry}
          material={materials['[Color_F21]']}
        />
      </group>
      <group position={[-0.831, 3.077, -6.002]} rotation={[-Math.PI, 0, 0]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Air_intake_1'].geometry}
          material={materials['Air intake']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Air_intake_2'].geometry}
          material={materials['[Color_F21]']}
        />
      </group>
      <group position={[-0.831, 3.077, 6.278]} rotation={[-Math.PI, 0, 0]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Air_intake_1'].geometry}
          material={materials['Air intake']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Air_intake_2'].geometry}
          material={materials['[Color_F21]']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Box#A'].geometry}
        material={materials['[Color_006]']}
        position={[-0.907, 0.227, 2.043]}
        scale={[0.8, 1.345, 0.333]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Box#A#1'].geometry}
        material={materials['[Color_006]']}
        position={[-1.007, 0.327, -3.377]}
        scale={[1, 0.828, 0.545]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Box#A001'].geometry}
        material={materials['[Color_006]']}
        position={[-0.907, 0.227, 0.843]}
        scale={[0.8, 1.345, 0.515]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Box#A002'].geometry}
        material={materials['[Color_006]']}
        position={[-0.907, 0.327, -1.917]}
        scale={[0.8, 1.172, 0.412]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Box#A003'].geometry}
        material={materials['[Color_006]']}
        position={[-0.907, 0.327, -0.907]}
        scale={[0.5, 1.172, 0.152]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Box#A004'].geometry}
        material={materials['[Color_006]']}
        position={[-0.857, 0.377, -1.407]}
        scale={[0.45, 1.086, 0.152]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Box#A005'].geometry}
        material={materials['[Color_006]']}
        position={[-0.907, 0.227, 3.143]}
        scale={[0.8, 1.345, 0.333]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Box#A006'].geometry}
        material={materials['[Color_006]']}
        position={[-0.907, 0.227, 4.243]}
        scale={[0.8, 1.345, 0.333]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Box#A007'].geometry}
        material={materials['[Color_006]']}
        position={[0.593, 0.227, -1.708]}
        rotation={[0, 0, Math.PI]}
        scale={[-0.8, -1.345, -0.333]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Box#A008'].geometry}
        material={materials['[Color_006]']}
        position={[0.593, 0.227, 3.392]}
        rotation={[0, 0, Math.PI]}
        scale={[-0.8, -1.345, -0.258]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Box#A009'].geometry}
        material={materials['[Color_006]']}
        position={[0.593, 0.227, 0.492]}
        rotation={[0, 0, Math.PI]}
        scale={[-0.8, -1.345, -0.333]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Box#A010'].geometry}
        material={materials['[Color_006]']}
        position={[0.593, 0.227, -0.608]}
        rotation={[0, 0, Math.PI]}
        scale={[-0.8, -1.345, -0.333]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Box#A011'].geometry}
        material={materials['[Color_006]']}
        position={[0.593, 0.227, 1.692]}
        rotation={[0, 0, Math.PI]}
        scale={[-0.8, -1.345, -0.515]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Box#A012'].geometry}
        material={materials['[Color_006]']}
        position={[0.593, 0.401, -4.008]}
        rotation={[0, 0, Math.PI]}
        scale={[-0.8, -1.045, -0.333]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Box#A013'].geometry}
        material={materials['[Color_006]']}
        position={[0.593, 0.285, -2.808]}
        rotation={[0, 0, Math.PI]}
        scale={[-0.8, -1.245, -0.167]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Box#A014'].geometry}
        material={materials['[Color_006]']}
        position={[-0.747, 0.578, -9.646]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.16, -0.74, -0.052]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Box#A015'].geometry}
        material={materials['[Color_006]']}
        position={[-0.747, 0.578, 8.672]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.16, 0.74, 0.052]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Box#C'].geometry}
        material={materials['[Color_F21]']}
        position={[-0.127, 3.575, -3.44]}
      />
      <group position={[0.633, 0.992, -10.007]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Bracket_1'].geometry}
          material={materials['[Color_003]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Bracket_2'].geometry}
          material={materials['[Color_F13]']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Bracket#B'].geometry}
        material={materials['[Color_F13]']}
        position={[0.628, 1.907, -9.956]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Bracket#B001'].geometry}
        material={materials['[Color_F13]']}
        position={[0.628, 1.387, -9.956]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={-1}
      />
      <group position={[-0.147, 0.992, -10.007]} rotation={[0, 0, Math.PI]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Bracket_1'].geometry}
          material={materials['[Color_003]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Bracket_2'].geometry}
          material={materials['[Color_F13]']}
        />
      </group>
      <group position={[-0.357, 3.558, 4.322]} scale={[1, 1, 1.2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Brake_resistance_1'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Brake_resistance_2'].geometry}
          material={materials['[Color_F21]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Brake_resistance_3'].geometry}
          material={materials['[Fencing_Mesh_Blue]']}
        />
      </group>
      <group position={[-0.357, 3.558, 3.837]} scale={[1, 1, 1.2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Brake_resistance_1'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Brake_resistance_2'].geometry}
          material={materials['[Color_F21]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Brake_resistance_3'].geometry}
          material={materials['[Fencing_Mesh_Blue]']}
        />
      </group>
      <group position={[-0.357, 3.558, 3.353]} scale={[1, 1, 1.2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Brake_resistance_1'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Brake_resistance_2'].geometry}
          material={materials['[Color_F21]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Brake_resistance_3'].geometry}
          material={materials['[Fencing_Mesh_Blue]']}
        />
      </group>
      <group position={[-0.357, 3.558, 2.868]} scale={[1, 1, 1.2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Brake_resistance_1'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Brake_resistance_2'].geometry}
          material={materials['[Color_F21]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Brake_resistance_3'].geometry}
          material={materials['[Fencing_Mesh_Blue]']}
        />
      </group>
      <group position={[-0.357, 3.558, 2.383]} scale={[1, 1, 1.2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Brake_resistance_1'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Brake_resistance_2'].geometry}
          material={materials['[Color_F21]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Brake_resistance_3'].geometry}
          material={materials['[Fencing_Mesh_Blue]']}
        />
      </group>
      <group position={[-1.007, 1.057, -8.374]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Cab_interior_1'].geometry}
          material={materials['[Color_000]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Cab_interior_2'].geometry}
          material={materials['[Color_003]']}
        />
      </group>
      <group position={[1.493, 1.057, 7.4]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Cab_interior_1'].geometry}
          material={materials['[Color_000]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Cab_interior_2'].geometry}
          material={materials['[Color_003]']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Cable'].geometry}
        material={materials['[Color_007]']}
        position={[-0.097, 3.575, -3.247]}
      />
      <group position={[0.493, 0.586, 9.547]} rotation={[0, 1.571, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Coupler_Scharfenberg'].geometry}
          material={materials['[Color_F21]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Coupler_Scharfenberg_1'].geometry}
          material={materials['[Color_007]']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Electric_connection'].geometry}
        material={materials['[Color_F21]']}
        position={[0.498, 0.696, 9.313]}
        rotation={[0, 0, -Math.PI]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Electric_connection001'].geometry}
        material={materials['[Color_F21]']}
        position={[-0.012, 0.696, 9.313]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Hose#A'].geometry}
        material={materials['[Color_007]']}
        position={[0.136, 0.445, 9.313]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Hose#A001'].geometry}
        material={materials['[Color_007]']}
        position={[0.349, 0.445, 9.313]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Hose#B'].geometry}
        material={materials['[Color_007]']}
        position={[0.328, 0.71, 9.313]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Hose#B001'].geometry}
        material={materials['[Color_007]']}
        position={[0.157, 0.71, 9.313]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object'].geometry}
        material={materials['[Color_F21]']}
        position={[0.189, 0.796, 9.542]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object001'].geometry}
        material={materials['[Color_F21]']}
        position={[0.336, 0.806, 9.439]}
        rotation={[0, 1.571, 0]}
      />
      <group position={[-0.851, 2.747, 8.925]} rotation={[0, -0.055, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Display_1'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Display_2'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Display_3'].geometry}
          material={materials['[Color_000]']}
        />
      </group>
      <group position={[1.448, 0.877, 6.925]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_1'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_2'].geometry}
          material={materials['[Color_000]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_3'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_4'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
      </group>
      <group position={[1.448, 0.877, 6.925]} rotation={[0, 0, Math.PI]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_1'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_2'].geometry}
          material={materials['[Color_000]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_3'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_4'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
      </group>
      <group position={[1.448, 0.877, -7.899]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_1'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_2'].geometry}
          material={materials['[Color_000]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_3'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_4'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
      </group>
      <group position={[1.448, 0.877, -7.899]} rotation={[0, 0, Math.PI]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_1'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_2'].geometry}
          material={materials['[Color_000]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_3'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_4'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
      </group>
      <group position={[-0.963, 0.877, -7.899]} rotation={[-Math.PI, 0, 0]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_1'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_2'].geometry}
          material={materials['[Color_000]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_3'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_4'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
      </group>
      <group position={[-0.963, 0.877, -7.899]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_1'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_2'].geometry}
          material={materials['[Color_000]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_3'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_4'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
      </group>
      <group position={[-0.963, 0.877, 6.925]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_1'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_2'].geometry}
          material={materials['[Color_000]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_3'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_4'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
      </group>
      <group position={[-0.963, 0.877, 6.925]} rotation={[-Math.PI, 0, 0]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_1'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_2'].geometry}
          material={materials['[Color_000]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_3'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Door#A_4'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Footstep#B'].geometry}
        material={materials['[Color_006]']}
        position={[1.443, 0.557, -7.501]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Footstep#B001'].geometry}
        material={materials['[Color_006]']}
        position={[-0.957, 0.557, 6.528]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <group position={[-1.057, 0.807, 8.983]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Frame_X10p'].geometry}
          material={materials['[Color_000]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Frame_X10p_1'].geometry}
          material={materials['[Color_F21]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Frame_X10p_2'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Frame_X10p_3'].geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Frame_X10p_4'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Frame_X10p_5'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Frame_X10p_6'].geometry}
          material={materials['[Color_007]']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Footstep#A'].geometry}
        material={materials['[Color_006]']}
        position={[1.463, 0.587, 8.45]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Footstep#A001'].geometry}
        material={materials['[Color_006]']}
        position={[1.463, 0.587, -8.974]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Footstep#A002'].geometry}
        material={materials['[Color_006]']}
        position={[-1.057, 0.587, 8.45]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Footstep#A003'].geometry}
        material={materials['[Color_006]']}
        position={[-1.057, 0.587, -8.974]}
      />
      <group position={[-1.057, 1.307, 0.413]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Logo_Roslagsbanan_1'].geometry}
          material={materials['[Color_000]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Logo_Roslagsbanan_2'].geometry}
          material={materials.Material}
        />
      </group>
      <group position={[1.543, 1.307, -1.387]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Logo_Roslagsbanan_1'].geometry}
          material={materials['[Color_000]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Logo_Roslagsbanan_2'].geometry}
          material={materials.Material}
        />
      </group>
      <group position={[-0.132, 1.057, -9.957]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Gable_door_1'].geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Gable_door_2'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Gable_door_3'].geometry}
          material={materials['[Color_000]']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Handrail#B'].geometry}
        material={materials['[Color_F21]']}
        position={[1.543, 1.112, 8.615]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Handrail#B001'].geometry}
        material={materials['[Color_F21]']}
        position={[1.543, 1.112, 7.835]}
        rotation={[0, 0, Math.PI]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Handrail#B002'].geometry}
        material={materials['[Color_F21]']}
        position={[1.543, 1.112, -8.809]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Handrail#B003'].geometry}
        material={materials['[Color_F21]']}
        position={[1.543, 1.112, -9.589]}
        rotation={[0, 0, Math.PI]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Handrail#B004'].geometry}
        material={materials['[Color_F21]']}
        position={[-1.057, 1.112, -9.589]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Handrail#B005'].geometry}
        material={materials['[Color_F21]']}
        position={[-1.057, 1.112, -8.809]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Handrail#B006'].geometry}
        material={materials['[Color_F21]']}
        position={[-1.057, 1.112, 7.835]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Handrail#B007'].geometry}
        material={materials['[Color_F21]']}
        position={[-1.057, 1.112, 8.615]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Handrail#C'].geometry}
        material={materials['[Color_F21]']}
        position={[1.543, 1.842, 8.585]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Handrail#C001'].geometry}
        material={materials['[Color_F21]']}
        position={[1.543, 1.842, -8.839]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Handrail#C002'].geometry}
        material={materials['[Color_F21]']}
        position={[-1.057, 1.842, -8.839]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Handrail#C003'].geometry}
        material={materials['[Color_F21]']}
        position={[-1.057, 1.842, 8.585]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Handrail#E'].geometry}
        material={materials['[Color_F21]']}
        position={[0.623, 2.087, -9.957]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Handrail#E001'].geometry}
        material={materials['[Color_F21]']}
        position={[-0.137, 2.087, -9.957]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <group position={[-0.927, 1.149, 8.982]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp_1'].geometry}
          material={materials['[Color_003]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp_2'].geometry}
          material={materials.Material}
        />
      </group>
      <group position={[-0.733, 1.149, 8.982]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp_1'].geometry}
          material={materials['[Color_003]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp_2'].geometry}
          material={materials.Material}
        />
      </group>
      <group position={[1.219, 1.149, 8.982]} rotation={[-Math.PI, 0, 0]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp001_1'].geometry}
          material={materials['[Color_003]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp001_2'].geometry}
          material={materials['[Color_001]']}
        />
      </group>
      <group position={[1.413, 1.149, 8.982]} rotation={[-Math.PI, 0, 0]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp001_1'].geometry}
          material={materials['[Color_003]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp001_2'].geometry}
          material={materials['[Color_001]']}
        />
      </group>
      <group position={[0.155, 3.116, 8.973]} rotation={[-Math.PI, 0, 0]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp002_1'].geometry}
          material={materials['[Color_003]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp002_2'].geometry}
          material={materials['[Color_A11]']}
        />
      </group>
      <group position={[0.507, 3.116, 8.973]} rotation={[-Math.PI, 0, 0]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp002_1'].geometry}
          material={materials['[Color_003]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp002_2'].geometry}
          material={materials['[Color_A11]']}
        />
      </group>
      <group position={[0.331, 3.116, 8.973]} rotation={[-Math.PI, 0, 0]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp001_1'].geometry}
          material={materials['[Color_003]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp001_2'].geometry}
          material={materials['[Color_001]']}
        />
      </group>
      <group position={[0.331, 3.116, -9.947]} rotation={[0, 0, -Math.PI]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp002_1'].geometry}
          material={materials['[Color_003]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp002_2'].geometry}
          material={materials['[Color_A11]']}
        />
      </group>
      <group position={[0.155, 3.116, -9.947]} rotation={[0, 0, -Math.PI]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp001_1'].geometry}
          material={materials['[Color_003]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp001_2'].geometry}
          material={materials['[Color_001]']}
        />
      </group>
      <group position={[-0.927, 1.149, -9.955]} rotation={[0, 0, -Math.PI]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp001_1'].geometry}
          material={materials['[Color_003]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp001_2'].geometry}
          material={materials['[Color_001]']}
        />
      </group>
      <group position={[-0.733, 1.149, -9.955]} rotation={[0, 0, -Math.PI]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp001_1'].geometry}
          material={materials['[Color_003]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp001_2'].geometry}
          material={materials['[Color_001]']}
        />
      </group>
      <group position={[1.219, 1.149, -9.955]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp_1'].geometry}
          material={materials['[Color_003]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp_2'].geometry}
          material={materials.Material}
        />
      </group>
      <group position={[1.413, 1.149, -9.955]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp_1'].geometry}
          material={materials['[Color_003]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp_2'].geometry}
          material={materials.Material}
        />
      </group>
      <group position={[-0.021, 3.116, -9.947]} rotation={[0, 0, -Math.PI]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp002_1'].geometry}
          material={materials['[Color_003]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Headlamp002_2'].geometry}
          material={materials['[Color_A11]']}
        />
      </group>
      <group position={[1.089, 1.547, 8.975]} rotation={[Math.PI, -0.055, 2.443]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Horn_1'].geometry}
          material={materials['[Color_F21]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Horn_2'].geometry}
          material={materials['[Color_007]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Horn_3'].geometry}
          material={materials['[Color_F13]']}
        />
      </group>
      <group position={[-0.051, 3.565, -5.706]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Insulator'].geometry}
          material={materials['[Color_007]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Insulator_1'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[-0.051, 3.626, -5.706]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Insulator'].geometry}
          material={materials['[Color_007]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Insulator_1'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[-1.037, 0.877, 8.963]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Interiour#A_1'].geometry}
          material={materials['[Color_E04]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Interiour#A_2'].geometry}
          material={materials['[Color_003]']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Lamp_box'].geometry}
        material={materials['[Color_F13]']}
        position={[-0.547, 1.137, 8.972]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Lamp_box001'].geometry}
        material={materials['[Color_F13]']}
        position={[1.033, 1.137, 8.972]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Lamp_box002'].geometry}
        material={materials['[Color_F13]']}
        position={[-0.547, 1.137, -9.945]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Lamp_box003'].geometry}
        material={materials['[Color_F13]']}
        position={[1.033, 1.137, -9.945]}
        rotation={[0, 0, -Math.PI]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Metal_plate'].geometry}
        material={materials['[Color_F21]']}
        position={[0.643, 0.907, 9.013]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Metal_plate001'].geometry}
        material={materials['[Color_F21]']}
        position={[-0.157, 0.907, 9.013]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Metal_plate002'].geometry}
        material={materials['[Color_F21]']}
        position={[-0.157, 0.907, -9.987]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Metal_plate003'].geometry}
        material={materials['[Color_F21]']}
        position={[0.643, 0.907, -9.987]}
        rotation={[0, 0, Math.PI]}
        scale={-1}
      />
      <group position={[1.566, 2.307, 8.652]} rotation={[0, 0.262, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G-Object014_1'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G-Object014_2'].geometry}
          material={materials['[Color_003]']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object015'].geometry}
        material={materials['[Color_008]']}
        position={[1.518, 2.497, 8.694]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object016'].geometry}
        material={materials['[Color_008]']}
        position={[1.471, 2.609, 8.705]}
      />
      <group position={[-1.081, 2.307, 8.652]} rotation={[-Math.PI, 0.262, 0]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G-Object017_1'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G-Object017_2'].geometry}
          material={materials['[Color_003]']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object018'].geometry}
        material={materials['[Color_008]']}
        position={[-1.033, 2.497, 8.694]}
        rotation={[Math.PI, Math.PI / 6, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object019'].geometry}
        material={materials['[Color_008]']}
        position={[-0.986, 2.609, 8.705]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <group position={[-1.056, 2.307, -9.597]} rotation={[Math.PI, -1.501, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G-Object020_1'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G-Object020_2'].geometry}
          material={materials['[Color_003]']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object021'].geometry}
        material={materials['[Color_008]']}
        position={[-1.05, 2.497, -9.662]}
        rotation={[Math.PI, -1.501, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object022'].geometry}
        material={materials['[Color_008]']}
        position={[-0.986, 2.609, -9.678]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <group position={[-0.93, 2.582, -8.13]} rotation={[0, 1.501, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G-Object023_1'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G-Object023_2'].geometry}
          material={materials['[Color_003]']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object024'].geometry}
        material={materials['[Color_008]']}
        position={[-0.936, 2.772, -8.065]}
        rotation={[0, 1.501, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object025'].geometry}
        material={materials['[Color_008]']}
        position={[-1, 2.884, -8.049]}
      />
      <group position={[1.542, 2.307, -9.597]} rotation={[0, -1.501, Math.PI]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G-Object026_1'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G-Object026_2'].geometry}
          material={materials['[Color_003]']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object027'].geometry}
        material={materials['[Color_008]']}
        position={[1.536, 2.497, -9.662]}
        rotation={[0, -1.501, Math.PI]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object028'].geometry}
        material={materials['[Color_008]']}
        position={[1.471, 2.609, -9.678]}
        rotation={[0, 0, -Math.PI]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['_C-Motor_boggi_(Loose_Mesh)'].geometry}
        material={materials['[Color_006]']}
        position={[-0.586, -0.031, 7.688]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Air_spring'].geometry}
        material={materials['[Color_006]']}
        position={[1.075, 0.626, 6.238]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Air_spring001'].geometry}
        material={materials['[Color_006]']}
        position={[-0.986, 0.626, 6.238]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Engine'].geometry}
        material={materials['[Color_006]']}
        position={[-0.1, 0.213, 7.311]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Engine001'].geometry}
        material={materials['[Color_006]']}
        position={[0.589, 0.213, 4.766]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Axle_box'].geometry}
        material={materials['[Color_006]']}
        position={[0.785, 0.311, 7.318]}
      />
      <group position={[0.975, 0.331, 6.788]} rotation={[0, 0, Math.PI]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[0.975, 0.331, 7.488]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[0.975, 0.331, 6.788]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[0.975, 0.331, 7.488]} rotation={[-Math.PI, 0, 0]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Axle_box001'].geometry}
        material={materials['[Color_006]']}
        position={[0.785, 0.311, 5.118]}
      />
      <group position={[0.975, 0.331, 4.588]} rotation={[0, 0, Math.PI]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[0.975, 0.331, 5.288]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[0.975, 0.331, 4.588]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[0.975, 0.331, 5.288]} rotation={[-Math.PI, 0, 0]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Axle_box002'].geometry}
        material={materials['[Color_006]']}
        position={[-0.296, 0.311, 7.318]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <group position={[-0.486, 0.331, 6.788]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[-0.486, 0.331, 7.488]} rotation={[-Math.PI, 0, 0]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[-0.486, 0.331, 6.788]} rotation={[0, 0, Math.PI]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[-0.486, 0.331, 7.488]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Axle_box003'].geometry}
        material={materials['[Color_006]']}
        position={[-0.296, 0.311, 5.118]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <group position={[-0.486, 0.331, 4.588]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[-0.486, 0.331, 5.288]} rotation={[-Math.PI, 0, 0]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[-0.486, 0.331, 4.588]} rotation={[0, 0, Math.PI]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[-0.486, 0.331, 5.288]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['_C-Sway_bar_(Loose_Mesh)'].geometry}
        material={materials['[Color_006]']}
        position={[-0.807, 0.304, 6.043]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Link'].geometry}
        material={materials['[Color_006]']}
        position={[-0.827, 0.448, 5.807]}
        rotation={[1.745, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['_C-Sway_bar_(Loose_Mesh)001'].geometry}
        material={materials['[Color_006]']}
        position={[1.293, 0.304, 6.043]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Link001'].geometry}
        material={materials['[Color_006]']}
        position={[1.313, 0.448, 5.807]}
        rotation={[-1.396, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-vertical_damper'].geometry}
        material={materials['[Color_006]']}
        position={[1.347, 0.351, 6.354]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-vertical_damper001'].geometry}
        material={materials['[Color_006]']}
        position={[-0.949, 0.351, 6.354]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Wheel_axle_Ø870_mm'].geometry}
        material={materials['[Color_006]']}
        position={[0.785, -0.056, 5.455]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Wheel_axle_Ø870_mm001'].geometry}
        material={materials['[Color_006]']}
        position={[0.785, -0.056, 7.655]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['_C-Motor_boggi_(Loose_Mesh)001'].geometry}
        material={materials['[Color_006]']}
        position={[-0.583, -0.031, -8.662]}
        rotation={[0, 0, Math.PI]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Air_spring002'].geometry}
        material={materials['[Color_006]']}
        position={[1.078, 0.626, -7.212]}
        rotation={[0, 0, Math.PI]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Air_spring003'].geometry}
        material={materials['[Color_006]']}
        position={[-0.983, 0.626, -7.212]}
        rotation={[0, 0, Math.PI]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Engine002'].geometry}
        material={materials['[Color_006]']}
        position={[-0.096, 0.213, -8.284]}
        rotation={[0, 0, Math.PI]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Engine003'].geometry}
        material={materials['[Color_006]']}
        position={[0.592, 0.213, -5.739]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Axle_box004'].geometry}
        material={materials['[Color_006]']}
        position={[0.788, 0.311, -8.292]}
        rotation={[0, 0, Math.PI]}
        scale={-1}
      />
      <group position={[0.978, 0.331, -7.762]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[0.978, 0.331, -8.462]} rotation={[0, 0, Math.PI]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[0.978, 0.331, -7.762]} rotation={[-Math.PI, 0, 0]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[0.978, 0.331, -8.462]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Axle_box005'].geometry}
        material={materials['[Color_006]']}
        position={[0.788, 0.311, -6.092]}
        rotation={[0, 0, Math.PI]}
        scale={-1}
      />
      <group position={[0.978, 0.331, -5.562]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[0.978, 0.331, -6.262]} rotation={[0, 0, Math.PI]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[0.978, 0.331, -5.562]} rotation={[-Math.PI, 0, 0]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[0.978, 0.331, -6.262]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Axle_box006'].geometry}
        material={materials['[Color_006]']}
        position={[-0.293, 0.311, -8.292]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <group position={[-0.483, 0.331, -7.762]} rotation={[-Math.PI, 0, 0]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[-0.483, 0.331, -8.462]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[-0.483, 0.331, -7.762]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[-0.483, 0.331, -8.462]} rotation={[0, 0, Math.PI]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Axle_box007'].geometry}
        material={materials['[Color_006]']}
        position={[-0.293, 0.311, -6.092]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <group position={[-0.483, 0.331, -5.562]} rotation={[-Math.PI, 0, 0]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[-0.483, 0.331, -6.262]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[-0.483, 0.331, -5.562]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <group position={[-0.483, 0.331, -6.262]} rotation={[0, 0, Math.PI]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_1'].geometry}
          material={materials['[Color_009]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Rubber_spring001_2'].geometry}
          material={materials['[Color_006]']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['_C-Sway_bar_(Loose_Mesh)002'].geometry}
        material={materials['[Color_006]']}
        position={[-0.804, 0.304, -7.016]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Link002'].geometry}
        material={materials['[Color_006]']}
        position={[-0.824, 0.448, -6.78]}
        rotation={[-1.745, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['_C-Sway_bar_(Loose_Mesh)003'].geometry}
        material={materials['[Color_006]']}
        position={[1.296, 0.304, -7.016]}
        rotation={[0, 0, Math.PI]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Link003'].geometry}
        material={materials['[Color_006]']}
        position={[1.316, 0.448, -6.78]}
        rotation={[1.396, 0, -Math.PI]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-vertical_damper002'].geometry}
        material={materials['[Color_006]']}
        position={[1.35, 0.351, -7.327]}
        rotation={[0, 0, Math.PI]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-vertical_damper003'].geometry}
        material={materials['[Color_006]']}
        position={[-0.946, 0.351, -7.327]}
        rotation={[0, 0, Math.PI]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Wheel_axle_Ø870_mm002'].geometry}
        material={materials['[Color_006]']}
        position={[0.788, -0.056, -6.428]}
        rotation={[-Math.PI, -1.571, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Wheel_axle_Ø870_mm003'].geometry}
        material={materials['[Color_006]']}
        position={[0.788, -0.056, -8.628]}
        rotation={[-Math.PI, -1.571, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['_C-Snow_plow_(Loose_Mesh)'].geometry}
        material={materials['[Color_006]']}
        position={[-0.883, 0.146, 8.268]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Plow'].geometry}
        material={materials['[Color_006]']}
        position={[0.038, 0.146, 8.414]}
        rotation={[-Math.PI, 0, 0]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Plow001'].geometry}
        material={materials['[Color_006]']}
        position={[0.447, 0.146, 8.414]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['_C-Snow_plow_(Loose_Mesh)001'].geometry}
        material={materials['[Color_006]']}
        position={[-0.88, 0.146, -9.241]}
        rotation={[0, 0, Math.PI]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Plow002'].geometry}
        material={materials['[Color_006]']}
        position={[0.041, 0.146, -9.387]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Plow003'].geometry}
        material={materials['[Color_006]']}
        position={[0.45, 0.146, -9.387]}
        rotation={[0, 0, Math.PI]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Socket'].geometry}
        material={materials['[Color_F21]']}
        position={[-0.373, 1.119, -9.965]}
        rotation={[Math.PI, -0.055, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-tank'].geometry}
        material={materials['[Color_006]']}
        position={[1.032, 0.569, -4.432]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Vent'].geometry}
        material={materials['[Color_F21]']}
        position={[-0.661, 3.538, -8.89]}
        rotation={[0, 0, 0.063]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Vent001'].geometry}
        material={materials['[Color_F21]']}
        position={[1.146, 3.538, -8.89]}
        rotation={[-Math.PI, 0, 0.063]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Vent002'].geometry}
        material={materials['[Color_F21]']}
        position={[1.146, 3.538, -4.89]}
        rotation={[-Math.PI, 0, 0.063]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Vent003'].geometry}
        material={materials['[Color_F21]']}
        position={[1.146, 3.538, -1.89]}
        rotation={[-Math.PI, 0, 0.063]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Vent004'].geometry}
        material={materials['[Color_F21]']}
        position={[-0.661, 3.538, 7.917]}
        rotation={[0, 0, -3.078]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Vent005'].geometry}
        material={materials['[Color_F21]']}
        position={[-0.661, 3.538, 0.917]}
        rotation={[0, 0, -3.078]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Vent006'].geometry}
        material={materials['[Color_F21]']}
        position={[-0.661, 3.538, 3.917]}
        rotation={[0, 0, -3.078]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Vent007'].geometry}
        material={materials['[Color_F21]']}
        position={[1.146, 3.538, 7.917]}
        rotation={[Math.PI, 0, -3.078]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Vent008'].geometry}
        material={materials['[Color_F21]']}
        position={[1.146, 3.538, -7.73]}
        rotation={[-Math.PI, 0, 0.063]}
        scale={-1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['C-Vent009'].geometry}
        material={materials['[Color_F21]']}
        position={[-0.661, 3.538, 6.757]}
        rotation={[0, 0, -3.078]}
        scale={-1}
      />
      <group position={[1.538, 1.957, 6.198]} rotation={[0, 0, 0.087]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_1'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_2'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_3'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
      </group>
      <group position={[1.538, 1.957, 3.128]} rotation={[0, 0, 0.087]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_1'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_2'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_3'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
      </group>
      <group position={[1.538, 1.957, 1.593]} rotation={[0, 0, 0.087]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_1'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_2'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_3'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
      </group>
      <group position={[1.538, 1.957, -1.477]} rotation={[0, 0, 0.087]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_1'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_2'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_3'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
      </group>
      <group position={[1.538, 1.957, -3.012]} rotation={[0, 0, 0.087]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_1'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_2'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_3'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
      </group>
      <group position={[1.538, 1.957, -6.082]} rotation={[0, 0, 0.087]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_1'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_2'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_3'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
      </group>
      <group position={[-1.053, 1.957, 6.198]} rotation={[-Math.PI, 0, 0.087]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_1'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_2'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_3'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
      </group>
      <group position={[-1.053, 1.957, -6.082]} rotation={[-Math.PI, 0, 0.087]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_1'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_2'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_3'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
      </group>
      <group position={[-1.053, 1.957, -1.477]} rotation={[-Math.PI, 0, 0.087]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_1'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_2'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_3'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
      </group>
      <group position={[-1.053, 1.957, 1.593]} rotation={[-Math.PI, 0, 0.087]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_1'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_2'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_3'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
      </group>
      <group position={[-1.053, 1.957, 3.128]} rotation={[-Math.PI, 0, 0.087]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_1'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_2'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_3'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
      </group>
      <group position={[-1.053, 1.957, -3.012]} rotation={[-Math.PI, 0, 0.087]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_1'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_2'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#A_3'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
      </group>
      <group position={[1.538, 1.957, 4.663]} rotation={[0, 0, 0.087]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_1'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_2'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_3'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_4'].geometry}
          material={materials['[Color_003]']}
        />
      </group>
      <group position={[1.538, 1.957, 0.058]} rotation={[0, 0, 0.087]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_1'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_2'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_3'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_4'].geometry}
          material={materials['[Color_003]']}
        />
      </group>
      <group position={[1.538, 1.957, -4.547]} rotation={[0, 0, 0.087]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_1'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_2'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_3'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_4'].geometry}
          material={materials['[Color_003]']}
        />
      </group>
      <group position={[-1.053, 1.957, -4.547]} rotation={[-Math.PI, 0, 0.087]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_1'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_2'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_3'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_4'].geometry}
          material={materials['[Color_003]']}
        />
      </group>
      <group position={[-1.053, 1.957, 4.663]} rotation={[-Math.PI, 0, 0.087]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_1'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_2'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_3'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_4'].geometry}
          material={materials['[Color_003]']}
        />
      </group>
      <group position={[-1.053, 1.957, 0.058]} rotation={[-Math.PI, 0, 0.087]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_1'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_2'].geometry}
          material={materials['[Color_008]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_3'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#B_4'].geometry}
          material={materials['[Color_003]']}
        />
      </group>
      <group position={[1.538, 1.957, 8.62]} rotation={[0, 0, 0.087]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#C_1'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#C_2'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#C_3'].geometry}
          material={materials['[Color_003]']}
        />
      </group>
      <group position={[-1.053, 1.957, 8.62]} rotation={[-Math.PI, 0, 0.087]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#C_1'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#C_2'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#C_3'].geometry}
          material={materials['[Color_003]']}
        />
      </group>
      <group position={[1.538, 1.957, -8.544]} rotation={[0, 0, 0.087]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#C_1'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#C_2'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#C_3'].geometry}
          material={materials['[Color_003]']}
        />
      </group>
      <group position={[-1.053, 1.957, -8.544]} rotation={[-Math.PI, 0, 0.087]} scale={-1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#C_1'].geometry}
          material={materials['[Color_F13]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#C_2'].geometry}
          material={materials['[Translucent_Glass_Gray]']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['C-Window#C_3'].geometry}
          material={materials['[Color_003]']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['_C-Wiper_(Loose_Mesh)'].geometry}
        material={materials['[Color_009]']}
        position={[-0.118, 1.875, 8.956]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object004'].geometry}
        material={materials['[Color_009]']}
        position={[0.217, 1.868, 9.017]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object005'].geometry}
        material={materials['[Color_009]']}
        position={[-0.029, 2.117, 8.998]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['_C-Wiper_(Loose_Mesh)001'].geometry}
        material={materials['[Color_009]']}
        position={[0.689, 1.875, 8.953]}
        rotation={[0, 0.055, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object006'].geometry}
        material={materials['[Color_009]']}
        position={[1.027, 1.868, 8.995]}
        rotation={[0, 0.055, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object007'].geometry}
        material={materials['[Color_009]']}
        position={[0.78, 2.117, 8.991]}
        rotation={[0, 0.055, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['_C-Wiper_(Loose_Mesh)002'].geometry}
        material={materials['[Color_009]']}
        position={[-0.924, 1.875, 8.913]}
        rotation={[0, -0.055, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object008'].geometry}
        material={materials['[Color_009]']}
        position={[-0.593, 1.868, 8.992]}
        rotation={[0, -0.055, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object009'].geometry}
        material={materials['[Color_009]']}
        position={[-0.838, 2.117, 8.961]}
        rotation={[0, -0.055, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['_C-Wiper_(Loose_Mesh)003'].geometry}
        material={materials['[Color_009]']}
        position={[-0.203, 1.875, -9.926]}
        rotation={[Math.PI, -0.055, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object010'].geometry}
        material={materials['[Color_009]']}
        position={[-0.541, 1.868, -9.969]}
        rotation={[Math.PI, -0.055, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object011'].geometry}
        material={materials['[Color_009]']}
        position={[-0.295, 2.117, -9.964]}
        rotation={[Math.PI, -0.055, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['_C-Wiper_(Loose_Mesh)004'].geometry}
        material={materials['[Color_009]']}
        position={[1.41, 1.875, -9.886]}
        rotation={[-Math.PI, 0.055, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object012'].geometry}
        material={materials['[Color_009]']}
        position={[1.079, 1.868, -9.966]}
        rotation={[-Math.PI, 0.055, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-Object013'].geometry}
        material={materials['[Color_009]']}
        position={[1.323, 2.117, -9.934]}
        rotation={[-Math.PI, 0.055, -Math.PI]}
      />
    </group>
  )
})
