/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Kemal Çolak (https://sketchfab.com/kemalcolak)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/yellow-black-road-barrier-94cf468d966d46f2aeae5264caa107b2
Title: Yellow-Black Road Barrier
*/

import * as THREE from 'three'
import * as React from "react";
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import BarrierModel from "./road_barrier.glb";

type GLTFResult = GLTF & {
  nodes: {
    Cube_Common_0: THREE.Mesh
    Cube002_Common_0: THREE.Mesh
  }
  materials: {
    Common: THREE.MeshStandardMaterial
  }
}

export function RoadBarrier(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(BarrierModel) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube_Common_0.geometry}
        material={materials.Common}
        scale={[0.1, 0.051, 0.051]}
      />
      <mesh
        geometry={nodes.Cube002_Common_0.geometry}
        material={materials.Common}
        position={[0, 0.944, 0]}
        rotation={[Math.PI, 0, 0]}
        scale={[0.112, 0.103, 0.066]}
      />
    </group>
  )
}

useGLTF.preload(BarrierModel)

